# Generated by Django 4.2.4 on 2023-09-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_uploadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmodel',
            old_name='aname',
            new_name='Assignment',
        ),
        migrations.RenameField(
            model_name='addmodel',
            old_name='rm',
            new_name='RMaterial',
        ),
        migrations.RenameField(
            model_name='addmodel',
            old_name='sname',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='sa',
            new_name='Submission',
        ),
    ]
