# Generated by Django 4.2.4 on 2023-10-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_rename_aname_addmodel_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('op1', models.CharField(max_length=40)),
                ('op2', models.CharField(max_length=40)),
                ('op3', models.CharField(max_length=40)),
                ('op1c', models.IntegerField(default=0)),
                ('op2c', models.IntegerField(default=0)),
                ('op3c', models.IntegerField(default=0)),
            ],
        ),
    ]
