# Generated by Django 4.2.4 on 2023-10-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_pollmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=30)),
                ('Chp_name', models.CharField(max_length=30)),
                ('Material', models.FileField(upload_to='')),
            ],
        ),
    ]
