# Generated by Django 4.2.4 on 2023-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_anotesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotesmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='anotesmodel',
            name='sid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
